"""Initial migration

Revision ID: e7da41f98753
Revises: 
Create Date: 2025-10-23 19:16:05.006237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7da41f98753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('clinical_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('ap_hi', sa.Integer(), nullable=False),
    sa.Column('ap_lo', sa.Integer(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('gluc', sa.Integer(), nullable=False),
    sa.Column('smoke', sa.Integer(), nullable=False),
    sa.Column('alco', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('correct_risk', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('ap_hi', sa.Integer(), nullable=False),
    sa.Column('ap_lo', sa.Integer(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('gluc', sa.Integer(), nullable=False),
    sa.Column('smoke', sa.Integer(), nullable=False),
    sa.Column('alco', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('predicted_risk', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casos_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caso_dados', sa.Text(), nullable=False),
    sa.Column('gabarito', sa.String(length=50), nullable=False),
    sa.Column('resposta_usuario', sa.String(length=50), nullable=False),
    sa.Column('acertou', sa.Boolean(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casos_historico')
    op.drop_table('prediction_logs')
    op.drop_table('clinical_cases')
    op.drop_table('users')
    # ### end Alembic commands ###
